#ifdef
FORMAT(JOBNAME, STRING)
FORMAT(JOBTYPE, OTHER)
FORMAT(GEOM, STRING)
FORMAT(BASIS, STRING)
FORMAT(MOVECS, OTHER)
FORMAT(MC_BASIS, STRING)
FORMAT(ELECTRON_PAIRS, INT)
FORMAT(MC_TRIAL, INT)
FORMAT(MC_DELX, DOUBLE)
FORMAT(NBLOCK, OTHER)
FORMAT(SPHERICAL, BOOL)
FORMAT(FREEZE_CORE, BOOL)
#endif
